const UserCard = [
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
  {
    fullNames: "Mugisha",
    email: "Success",
    location: "",
    books: 43,
    complete: 43,
    incomplete: 0,
  },
];
export default UserCard